#ifndef PROPERTY_H_INCLUDED
#define PROPERTY_H_INCLUDED

#define SCREEN_WIDTH   700
#define SCREEN_HEIGHT  850

#define PLAYER_SPEED    5

#define MAX_KEYBOARD_KEYS 350

#define SPEEDRUNWAY 8

#endif
